# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    steps:
      - run: yarn build
  test:
    steps:
      - run: yarn test
# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "Welcome"
  build_and_test:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test